# Creating

In [2]:
import pandas as pd
import numpy as np

In [9]:
label_folder = "./CICIDS/Raw"
output_file = "./CICIDS/Raw/CICIDS2017_preprocessed.csv"
df1 = pd.read_csv(label_folder + "/Monday-WorkingHours.pcap_ISCX.csv")
df2 = pd.read_csv(label_folder + "/Tuesday-WorkingHours.pcap_ISCX.csv")
df3 = pd.read_csv(label_folder + "/Wednesday-workingHours.pcap_ISCX.csv")
df4 = pd.read_csv(label_folder + "/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
df5 = pd.read_csv(
    label_folder + "/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    encoding="cp1252",
    low_memory=False,
)
df6 = pd.read_csv(label_folder + "/Friday-WorkingHours-Morning.pcap_ISCX.csv")
df7 = pd.read_csv(label_folder + "/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")
df8 = pd.read_csv(label_folder + "/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

In [10]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8], ignore_index=True)
df.shape

(3119345, 85)

In [11]:
df.columns = df.columns.str.strip()
## Duplicate Column; Removal
df.drop(columns=["Fwd Header Length.1"], inplace=True)
df.shape

(3119345, 84)

In [12]:
df = df.drop(df[pd.isnull(df["Flow ID"])].index)
df.shape

(2830743, 84)

In [13]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
df.shape

(2827876, 84)

In [14]:
df.drop_duplicates(inplace=True)
df.shape

(2827677, 84)

In [15]:
df

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-8.254.250.126-49188-80-6,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,4.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.5-8.254.250.126-49188-80-6,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.14-8.253.185.121-49486-80-6,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
5,192.168.10.14-8.253.185.121-49486-80-6,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
8,192.168.10.3-192.168.10.9-88-1031-6,192.168.10.9,1031.0,192.168.10.3,88.0,6.0,03/07/2017 08:56:38,609.0,7.0,4.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119340,192.168.10.15-72.21.91.29-61374-80-6,72.21.91.29,80.0,192.168.10.15,61374.0,6.0,7/7/2017 5:02,61.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119341,192.168.10.15-72.21.91.29-61378-80-6,72.21.91.29,80.0,192.168.10.15,61378.0,6.0,7/7/2017 5:02,72.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119342,192.168.10.15-72.21.91.29-61375-80-6,72.21.91.29,80.0,192.168.10.15,61375.0,6.0,7/7/2017 5:02,75.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119343,192.168.10.15-8.41.222.187-61323-80-6,8.41.222.187,80.0,192.168.10.15,61323.0,6.0,7/7/2017 5:02,48.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119344,192.168.10.15-8.43.72.21-61326-80-6,8.43.72.21,80.0,192.168.10.15,61326.0,6.0,7/7/2017 5:02,68.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [19]:
df.rename(columns={'Source IP': 'source_ip', 'Destination IP': 'destination_ip', 'Source Port': 'source_port', 'Destination Port': 'destination_port', 'Protocol': 'protocol', 'Label':'attack_label'}, inplace=True)

In [20]:
df.drop('Flow ID', axis=1, inplace=True)

In [21]:
df

,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,4.0,2.0,0.0,12.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,1.0,2.0,0.0,12.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,3.0,2.0,0.0,12.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
5,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,1.0,2.0,0.0,12.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
8,192.168.10.9,1031.0,192.168.10.3,88.0,6.0,03/07/2017 08:56:38,609.0,7.0,4.0,484.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119340,72.21.91.29,80.0,192.168.10.15,61374.0,6.0,7/7/2017 5:02,61.0,1.0,1.0,6.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119341,72.21.91.29,80.0,192.168.10.15,61378.0,6.0,7/7/2017 5:02,72.0,1.0,1.0,6.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119342,72.21.91.29,80.0,192.168.10.15,61375.0,6.0,7/7/2017 5:02,75.0,1.0,1.0,6.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119343,8.41.222.187,80.0,192.168.10.15,61323.0,6.0,7/7/2017 5:02,48.0,2.0,0.0,12.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3119344,8.43.72.21,80.0,192.168.10.15,61326.0,6.0,7/7/2017 5:02,68.0,1.0,1.0,6.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [24]:
start_value = 1
end_value = start_value + len(df)
df['flow_id'] = range(start_value, end_value)

In [25]:
df

,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label,flow_id
0,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,4.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,1
1,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,1.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2
4,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,3.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,3
5,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,1.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,4
8,192.168.10.9,1031.0,192.168.10.3,88.0,6.0,03/07/2017 08:56:38,609.0,7.0,4.0,484.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119340,72.21.91.29,80.0,192.168.10.15,61374.0,6.0,7/7/2017 5:02,61.0,1.0,1.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2827673
3119341,72.21.91.29,80.0,192.168.10.15,61378.0,6.0,7/7/2017 5:02,72.0,1.0,1.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2827674
3119342,72.21.91.29,80.0,192.168.10.15,61375.0,6.0,7/7/2017 5:02,75.0,1.0,1.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2827675
3119343,8.41.222.187,80.0,192.168.10.15,61323.0,6.0,7/7/2017 5:02,48.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2827676
3119344,8.43.72.21,80.0,192.168.10.15,61326.0,6.0,7/7/2017 5:02,68.0,1.0,1.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,2827677

In [26]:
flow_id = df.pop('flow_id')
df.insert(0, 'flow_id', flow_id)

In [27]:
df.reset_index(drop=True, inplace=True)

In [28]:
df.rename_axis(None, inplace=True)

In [29]:
df

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,4.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,2,8.254.250.126,80.0,192.168.10.5,49188.0,6.0,03/07/2017 08:55:58,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,4,8.253.185.121,80.0,192.168.10.14,49486.0,6.0,03/07/2017 08:56:22,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,6.0,03/07/2017 08:56:38,609.0,7.0,4.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827672,2827673,72.21.91.29,80.0,192.168.10.15,61374.0,6.0,7/7/2017 5:02,61.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827673,2827674,72.21.91.29,80.0,192.168.10.15,61378.0,6.0,7/7/2017 5:02,72.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827674,2827675,72.21.91.29,80.0,192.168.10.15,61375.0,6.0,7/7/2017 5:02,75.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827675,2827676,8.41.222.187,80.0,192.168.10.15,61323.0,6.0,7/7/2017 5:02,48.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827676,2827677,8.43.72.21,80.0,192.168.10.15,61326.0,6.0,7/7/2017 5:02,68.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [31]:
df["protocol"] = df["protocol"].astype(str)
df["protocol"] = df["protocol"].apply(lambda x: x.replace("6.0", "tcp"))
df["protocol"] = df["protocol"].apply(lambda x: x.replace("17.0", "udp"))
df["protocol"] = df["protocol"].apply(lambda x: x.replace("0.0", "other"))

In [32]:
df

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,4.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,2,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,4,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp,03/07/2017 08:56:38,609.0,7.0,4.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827672,2827673,72.21.91.29,80.0,192.168.10.15,61374.0,tcp,7/7/2017 5:02,61.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827673,2827674,72.21.91.29,80.0,192.168.10.15,61378.0,tcp,7/7/2017 5:02,72.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827674,2827675,72.21.91.29,80.0,192.168.10.15,61375.0,tcp,7/7/2017 5:02,75.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827675,2827676,8.41.222.187,80.0,192.168.10.15,61323.0,tcp,7/7/2017 5:02,48.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827676,2827677,8.43.72.21,80.0,192.168.10.15,61326.0,tcp,7/7/2017 5:02,68.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [34]:
df.to_csv('./CICIDS/Export/CICIDS_Flow.csv', index=False)

# Processing

In [53]:
df1 = pd.read_csv('./CICIDS/output6.csv')

/tmp/ipykernel_3112316/1366810060.py:1: DtypeWarning: Columns (16,18,37,48,49,50,52,55,63,68,69,70,71,72,73,74,75,76,79,81,82,84,89,90,91,92,93,94,95,96,102,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,130,133,134,135,137,138,141,145,150,151,152,153,154,155,156,157,160,161,162,163,164,166,167,168,169,170,171,172,173,174,175,176,177,178,179,183,184,185,186,187,188,189,190,191,193,194,195,196,197,198,199,201,202,204,205,206) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('./CICIDS/output6.csv')

In [54]:
df1.rename(columns={'packet': 'packet_hex', 'payload': 'payload_hex', 'srcip': 'source_ip', 'dstip': 'destination_ip', 'sport': 'source_port', 'dsport': 'destination_port', 'protocol_m': 'protocol'}, inplace=True)

In [55]:
df1

,stime,source_ip,source_port,destination_ip,destination_port,protocol,sttl,total_len,first_layer,packet_hex,...,DNS qd,Kerberos options,Kerberos address,IP copy_flag,IP optclass,IP option,IP length,IP alert,Kerberos flags,Kerberos sname
0,1.499263e+09,192.168.10.14,52028.0,23.208.102.104,443.0,tcp,128.0,41.0,Ethernet,00c1b114eb31b8ac6f3607ee0800450000292897400080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.499263e+09,192.168.10.19,35443.0,23.208.106.95,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034549e400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.499263e+09,192.168.10.19,35441.0,23.208.106.95,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034a8f0400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.499263e+09,192.168.10.17,43828.0,104.88.54.24,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9b9567080045000034f292400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.499263e+09,192.168.10.15,55959.0,192.168.10.3,53.0,udp,128.0,79.0,Ethernet,1866da9be37d001e4fd4ca2808004500004f0b71000080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999996,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999997,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999998,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999999,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf4400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
flow1 = pd.read_csv('./CICIDS/Export/CICIDS_Flow.csv')

In [4]:
flow1

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,4.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,2,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,4,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp,03/07/2017 08:56:38,609.0,7.0,4.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827672,2827673,72.21.91.29,80.0,192.168.10.15,61374.0,tcp,7/7/2017 5:02,61.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827673,2827674,72.21.91.29,80.0,192.168.10.15,61378.0,tcp,7/7/2017 5:02,72.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827674,2827675,72.21.91.29,80.0,192.168.10.15,61375.0,tcp,7/7/2017 5:02,75.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827675,2827676,8.41.222.187,80.0,192.168.10.15,61323.0,tcp,7/7/2017 5:02,48.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827676,2827677,8.43.72.21,80.0,192.168.10.15,61326.0,tcp,7/7/2017 5:02,68.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [37]:
flow1 = flow1[['flow_id', 'source_ip', 'source_port', 'destination_ip', 'destination_port', 'protocol']]

In [3]:
flow1

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,4.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,2,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,03/07/2017 08:55:58,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,3.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,4,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,03/07/2017 08:56:22,1.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp,03/07/2017 08:56:38,609.0,7.0,4.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827672,2827673,72.21.91.29,80.0,192.168.10.15,61374.0,tcp,7/7/2017 5:02,61.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827673,2827674,72.21.91.29,80.0,192.168.10.15,61378.0,tcp,7/7/2017 5:02,72.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827674,2827675,72.21.91.29,80.0,192.168.10.15,61375.0,tcp,7/7/2017 5:02,75.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827675,2827676,8.41.222.187,80.0,192.168.10.15,61323.0,tcp,7/7/2017 5:02,48.0,2.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2827676,2827677,8.43.72.21,80.0,192.168.10.15,61326.0,tcp,7/7/2017 5:02,68.0,1.0,1.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [39]:
flow2 = flow1.copy()

In [40]:
flow2.rename(columns={'source_ip': 'destination_ip', 'destination_ip': 'source_ip', 'source_port': 'destination_port', 'destination_port': 'source_port'}, inplace=True)

In [58]:
flow2

,flow_id,destination_ip,destination_port,source_ip,source_port,protocol
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp
1,2,8.254.250.126,80.0,192.168.10.5,49188.0,tcp
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp
3,4,8.253.185.121,80.0,192.168.10.14,49486.0,tcp
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp
...,...,...,...,...,...,...
2827672,2827673,72.21.91.29,80.0,192.168.10.15,61374.0,tcp
2827673,2827674,72.21.91.29,80.0,192.168.10.15,61378.0,tcp
2827674,2827675,72.21.91.29,80.0,192.168.10.15,61375.0,tcp
2827675,2827676,8.41.222.187,80.0,192.168.10.15,61323.0,tcp
2827676,2827677,8.43.72.21,80.0,192.168.10.15,61326.0,tcp

In [42]:
flow = pd.concat([flow1, flow2])

In [59]:
flow

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp
5,6,192.168.10.9,1032.0,192.168.10.3,88.0,tcp
6,7,192.168.10.9,1033.0,192.168.10.3,88.0,tcp
...,...,...,...,...,...,...
2827623,2827624,192.168.10.3,389.0,192.168.10.51,60852.0,udp
2827624,2827625,184.84.243.218,80.0,192.168.10.8,10399.0,tcp
2827625,2827626,192.168.10.3,389.0,192.168.10.8,56007.0,udp
2827636,2827637,192.168.10.3,389.0,192.168.10.8,50690.0,udp
2827641,2827642,192.168.10.3,445.0,192.168.10.8,10414.0,tcp

In [44]:
flow.drop_duplicates(subset=flow.columns.difference(['flow_id']), inplace=True)

In [60]:
flow

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol
0,1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp
2,3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp
4,5,192.168.10.9,1031.0,192.168.10.3,88.0,tcp
5,6,192.168.10.9,1032.0,192.168.10.3,88.0,tcp
6,7,192.168.10.9,1033.0,192.168.10.3,88.0,tcp
...,...,...,...,...,...,...
2827623,2827624,192.168.10.3,389.0,192.168.10.51,60852.0,udp
2827624,2827625,184.84.243.218,80.0,192.168.10.8,10399.0,tcp
2827625,2827626,192.168.10.3,389.0,192.168.10.8,56007.0,udp
2827636,2827637,192.168.10.3,389.0,192.168.10.8,50690.0,udp
2827641,2827642,192.168.10.3,445.0,192.168.10.8,10414.0,tcp

In [61]:
df1

,stime,source_ip,source_port,destination_ip,destination_port,protocol,sttl,total_len,first_layer,packet_hex,...,DNS qd,Kerberos options,Kerberos address,IP copy_flag,IP optclass,IP option,IP length,IP alert,Kerberos flags,Kerberos sname
0,1.499263e+09,192.168.10.14,52028.0,23.208.102.104,443.0,tcp,128.0,41.0,Ethernet,00c1b114eb31b8ac6f3607ee0800450000292897400080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.499263e+09,192.168.10.19,35443.0,23.208.106.95,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034549e400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.499263e+09,192.168.10.19,35441.0,23.208.106.95,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034a8f0400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.499263e+09,192.168.10.17,43828.0,104.88.54.24,443.0,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9b9567080045000034f292400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.499263e+09,192.168.10.15,55959.0,192.168.10.3,53.0,udp,128.0,79.0,Ethernet,1866da9be37d001e4fd4ca2808004500004f0b71000080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999996,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999997,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999998,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999999,1.499343e+09,13.107.4.50,80.0,192.168.10.15,49910.0,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf4400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df1['source_port'] = df1['source_port'].astype(int)
df1['destination_port'] = df1['destination_port'].astype(int)

In [48]:
columns_to_match = ['source_ip', 'source_port', 'destination_ip', 'destination_port', 'protocol']

In [63]:
merged_df = df1.merge(flow, on=columns_to_match, how='left')

In [64]:
merged_df

,stime,source_ip,source_port,destination_ip,destination_port,protocol,sttl,total_len,first_layer,packet_hex,...,Kerberos options,Kerberos address,IP copy_flag,IP optclass,IP option,IP length,IP alert,Kerberos flags,Kerberos sname,flow_id
0,1.499263e+09,192.168.10.14,52028,23.208.102.104,443,tcp,128.0,41.0,Ethernet,00c1b114eb31b8ac6f3607ee0800450000292897400080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1206778
1,1.499263e+09,192.168.10.19,35443,23.208.106.95,443,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034549e400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1211004
2,1.499263e+09,192.168.10.19,35441,23.208.106.95,443,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9badb3080045000034a8f0400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1211010
3,1.499263e+09,192.168.10.17,43828,104.88.54.24,443,tcp,64.0,52.0,Ethernet,00c1b114eb310023ae9b9567080045000034f292400040...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1222888
4,1.499263e+09,192.168.10.15,55959,192.168.10.3,53,udp,128.0,79.0,Ethernet,1866da9be37d001e4fd4ca2808004500004f0b71000080...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,904284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960483
9999996,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf8400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960483
9999997,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960483
9999998,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf6400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960483
9999999,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,001e4fd4ca2800c1b114eb31080045000b903cf4400076...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960483

In [65]:
flow_id = merged_df.pop('flow_id')
merged_df.insert(0, 'flow_id', flow_id)

In [66]:
merged_df

,flow_id,stime,source_ip,source_port,destination_ip,destination_port,protocol,sttl,total_len,first_layer,...,DNS qd,Kerberos options,Kerberos address,IP copy_flag,IP optclass,IP option,IP length,IP alert,Kerberos flags,Kerberos sname
0,1206778,1.499263e+09,192.168.10.14,52028,23.208.102.104,443,tcp,128.0,41.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1211004,1.499263e+09,192.168.10.19,35443,23.208.106.95,443,tcp,64.0,52.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1211010,1.499263e+09,192.168.10.19,35441,23.208.106.95,443,tcp,64.0,52.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1222888,1.499263e+09,192.168.10.17,43828,104.88.54.24,443,tcp,64.0,52.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,904284,1.499263e+09,192.168.10.15,55959,192.168.10.3,53,udp,128.0,79.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,1960483,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999996,1960483,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999997,1960483,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999998,1960483,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999999,1960483,1.499343e+09,13.107.4.50,80,192.168.10.15,49910,tcp,118.0,2960.0,Ethernet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Testing

In [67]:
merged_df.flow_id.isna().sum()

0

In [271]:
merged_df.iloc[13]

stime                                1421927414
source_ip                           10.40.182.3
source_port                                   0
destination_ip                      10.40.182.1
destination_port                              0
                                       ...
HSRP MD5 Authentication sourceip            NaN
HSRP MD5 Authentication keyid               NaN
SCTPChunkInit addr                          NaN
flow_id                                148629.0
protocol_y                                  arp
Name: 13, Length: 389, dtype: object

In [254]:
flow[flow.protocol=='others']

Empty DataFrame
Columns: [flow_id, source_ip, source_port, destination_ip, destination_port, protocol]
Index: []

In [272]:
flow[(flow['source_ip']=='10.40.182.3') & (flow['destination_ip']=='10.40.182.1') & (flow['source_port']==0)]

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol
1966462,521,10.40.182.3,0,10.40.182.1,0,others

In [212]:
flow[(flow['source_ip']=='59.166.0.3') & (flow['destination_ip']=='149.171.126.4') & (flow['source_port']==6103) & (flow['destination_port']=='52633')]

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol
111536,115902,59.166.0.3,6103,149.171.126.4,52633,tcp

In [175]:
merged_df.flow_id.value_counts(dropna=False)

NaN         9935521
664410.0       1904
791440.0       1312
806229.0       1308
752940.0       1308
             ...
346583.0          4
723549.0          4
821934.0          2
189265.0          2
149675.0          2
Name: flow_id, Length: 847, dtype: int64

In [7]:
del df

In [13]:
df = pd.read_csv('./CICIDS/Export/Packet-Fields/Packet_Fields_File_1.csv')

/tmp/ipykernel_3440497/1533487670.py:1: DtypeWarning: Columns (25,37,38,40,43,51,56,57,58,59,60,61,63,64,65,66,67,70,71,72,73,74,75,76,78,83,84,85,86,87,88,89,90,96,100,101,102,103,104,105,106,107,108,109,110,111,112,113,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,134,138,142,144,145,148,149,150,152) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./CICIDS/Export/Packet-Fields/Packet_Fields_File_1.csv')

In [14]:
df

,packet_id,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,packet_hex,payload_hex,Ethernet dst,...,PPTP data,PPTP Incoming Call Connected len,PPTP Incoming Call Connected type,PPTP Outgoing Call Reply len,PPTP Outgoing Call Reply type,PPTP Outgoing Call Reply call_id,Skinny len,Skinny res,Skinny msg,attack_label
0,11952482,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b905b26400077...,b0324fc9a453eadd23fefd8cc2b96da89210015fd420ab...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
1,11952483,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b905b28400077...,6f2d76414e7acb086a62445556218cd2f21ad54483cd95...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
2,11952485,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb310800450005dc5b2a400077...,9b42249338c0f7bd5019393a265532dbae266d32a8418c...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
3,11952487,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b905b2b400077...,582baa0225e7949925e6747162dbc2f350c554ab64ee36...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
4,11952489,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b905b2d400077...,e11d7365760201b310a2eb99a4430d6bd1f8ebdec35d76...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2588702,16952477,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b901345400077...,ec414b08efb94aa70cf0a5ed9e9654e1d2686aeade1470...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
2588703,16952478,542647,192.168.10.14,50128,13.107.4.50,80,tcp,00c1b114eb31b8ac6f3607ee08004500002852b9400080...,000000000000,00:c1:b1:14:eb:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
2588704,16952479,548448,13.107.4.50,80,192.168.10.14,50128,tcp,b8ac6f3607ee00c1b114eb31080045000b90133f400077...,d7be298a6488d285a1b4cc1bdc0cb1215d68957349ca13...,b8:ac:6f:36:07:ee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
2588705,16952480,545288,192.168.10.15,50023,13.107.4.50,80,tcp,00c1b114eb31001e4fd4ca2808004500002837f2400080...,000000000000,00:c1:b1:14:eb:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
2588706,16952481,545288,192.168.10.15,50023,13.107.4.50,80,tcp,00c1b114eb31001e4fd4ca280800450000283823400080...,000000000000,00:c1:b1:14:eb:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN

In [7]:
flow1.attack_label.value_counts(dropna=False)

BENIGN                        100000
DDoS                          100000
DoS Hulk                      100000
PortScan                      100000
DoS GoldenEye                  10293
FTP-Patator                     7935
SSH-Patator                     5897
DoS slowloris                   5796
DoS Slowhttptest                5499
Bot                             1956
Web Attack – Brute Force        1507
Web Attack – XSS                 652
Infiltration                      36
Web Attack – Sql Injection        21
Heartbleed                        11
Name: attack_label, dtype: int64

In [6]:
flow1 = flow1.groupby('attack_label').apply(lambda x: x.sample(min(len(x), 100000))).reset_index(drop=True)

In [10]:
flow1

,flow_id,source_ip,source_port,destination_ip,destination_port,protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,attack_label
0,1421252,192.168.10.3,60311.0,192.168.10.1,53.0,udp,5/7/2017 2:44,48190.0,1.0,1.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,BENIGN
1,1843601,192.168.10.8,35284.0,192.168.10.14,5555.0,tcp,6/7/2017 3:28,3.0,2.0,0.0,...,24.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,BENIGN
2,1520000,172.217.12.174,80.0,192.168.10.9,22976.0,tcp,5/7/2017 3:56,51.0,1.0,1.0,...,20.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,BENIGN
3,2252114,192.168.10.8,3131.0,52.39.237.157,443.0,tcp,7/7/2017 11:06,63094225.0,17.0,17.0,...,20.0,568211.8333,1182762.664,2982516.0,85189.0,9947454.167,82386.26616,9995414.0,9794892.0,BENIGN
4,1928644,192.168.10.8,1915.0,35.156.199.43,80.0,tcp,6/7/2017 4:35,103.0,2.0,0.0,...,20.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439598,2030906,172.16.0.1,55942.0,192.168.10.50,80.0,tcp,6/7/2017 10:22,5993237.0,3.0,1.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,Web Attack – XSS
439599,2035394,172.16.0.1,59772.0,192.168.10.50,80.0,tcp,6/7/2017 10:27,5334912.0,3.0,1.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,Web Attack – XSS
439600,2030496,172.16.0.1,55444.0,192.168.10.50,80.0,tcp,6/7/2017 10:21,5952394.0,3.0,1.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,Web Attack – XSS
439601,2029813,172.16.0.1,54268.0,192.168.10.50,80.0,tcp,6/7/2017 10:20,345.0,2.0,0.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,Web Attack – XSS
439602,2029711,172.16.0.1,54808.0,192.168.10.50,80.0,tcp,6/7/2017 10:20,5586384.0,3.0,1.0,...,32.0,0.0000,0.000,0.0,0.0,0.000,0.00000,0.0,0.0,Web Attack – XSS

In [8]:
from pycaret.classification import *
s = setup(flow1, target = 'attack_label', normalize = True, fix_imbalance=True, use_gpu=True, feature_selection = True, session_id = 123)

Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa35bfc2b80>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8dadc0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8dadc0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa36a7979d0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa36a7979d0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8daf70>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa36a7979d0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8da1f0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8da1f0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8da280>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a9bd310>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40a8dadc0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa366d44b80>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40cdfb430>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40cdfb4c0>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40cdfb430>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fa40ab25670>
Traceback (most recent call last):
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/opt/jupyter-hub/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)

[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
[LightGBM] [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1

In [9]:
rf = create_model('rf')

In [11]:
evaluate_model(rf)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [12]:
flow1.columns

Index(['flow_id', 'source_ip', 'source_port', 'destination_ip',
       'destination_port', 'protocol', 'Timestamp', 'Flow Duration',
       'Total Fwd Packets', 'Total Backward Packets',
       'Total Length of Fwd Packets', 'Total Length of Bwd Packets',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'attack_label'],
      dtype='object')

In [5]:
flow1 = flow1[['source_ip', 'source_port', 'destination_ip', 'destination_port', 'protocol', 'Fwd Packets/s', 'Bwd Packets/s', 'Flow Bytes/s', 'attack_label']]

In [6]:
flow1

,source_ip,source_port,destination_ip,destination_port,protocol,Fwd Packets/s,Bwd Packets/s,Flow Bytes/s,attack_label
0,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,5.000000e+05,0.000000,3.000000e+06,BENIGN
1,8.254.250.126,80.0,192.168.10.5,49188.0,tcp,2.000000e+06,0.000000,1.200000e+07,BENIGN
2,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,6.666667e+05,0.000000,4.000000e+06,BENIGN
3,8.253.185.121,80.0,192.168.10.14,49486.0,tcp,2.000000e+06,0.000000,1.200000e+07,BENIGN
4,192.168.10.9,1031.0,192.168.10.3,88.0,tcp,1.149425e+04,6568.144499,1.474548e+06,BENIGN
...,...,...,...,...,...,...,...,...,...
2827672,72.21.91.29,80.0,192.168.10.15,61374.0,tcp,1.639344e+04,16393.442620,1.967213e+05,BENIGN
2827673,72.21.91.29,80.0,192.168.10.15,61378.0,tcp,1.388889e+04,13888.888890,1.666667e+05,BENIGN
2827674,72.21.91.29,80.0,192.168.10.15,61375.0,tcp,1.333333e+04,13333.333330,1.600000e+05,BENIGN
2827675,8.41.222.187,80.0,192.168.10.15,61323.0,tcp,4.166667e+04,0.000000,2.500000e+05,BENIGN
2827676,8.43.72.21,80.0,192.168.10.15,61326.0,tcp,1.470588e+04,14705.882350,1.764706e+05,BENIGN

In [7]:
flow2 = pd.read_csv('./unsw_flow1.csv')

In [8]:
flow2

,source_ip,source_port,destination_ip,destination_port,protocol,dur,sbytes,dbytes,sload,dload,spkts,dpkts,attack_label
0,59.166.0.0,1390,149.171.126.6,53,udp,0.001055,132,164,500473.937500,6.218009e+05,2,2,normal
1,59.166.0.0,33661,149.171.126.9,1024,udp,0.036133,528,304,87676.085940,5.048017e+04,4,4,normal
2,59.166.0.6,1464,149.171.126.7,53,udp,0.001119,146,178,521894.531300,6.362824e+05,2,2,normal
3,59.166.0.5,3593,149.171.126.5,53,udp,0.001209,132,164,436724.562500,5.425972e+05,2,2,normal
4,59.166.0.3,49664,149.171.126.0,53,udp,0.001169,146,178,499572.250000,6.090676e+05,2,2,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2059410,59.166.0.1,38606,149.171.126.9,80,tcp,0.564998,14106,772406,198981.250000,1.091598e+07,262,526,normal
2059411,59.166.0.1,38606,149.171.126.9,80,tcp,0.564998,14106,772406,198981.250000,1.091598e+07,262,526,normal
2059412,59.166.0.5,33094,149.171.126.7,43433,tcp,0.087306,320,1828,24465.671880,1.466108e+05,6,8,normal
2059413,59.166.0.9,35433,149.171.126.0,80,tcp,2.200934,3498,166054,12496.513670,5.983751e+05,58,116,normal
2059414,175.45.176.0,17293,149.171.126.17,110,tcp,0.942984,574,676,4470.913574,5.259898e+03,12,12,exploits

In [9]:
flow2['Fwd Packets/s'] = flow2['spkts']/flow2['dur']

In [10]:
flow2['Bwd Packets/s'] = flow2['dpkts']/flow2['dur']

In [11]:
flow2['Flow Bytes/s'] = (flow2['sbytes']+flow2['dbytes'])/flow2['dur']

In [12]:
flow2 = flow2[['source_ip', 'source_port', 'destination_ip', 'destination_port', 'protocol', 'Fwd Packets/s', 'Bwd Packets/s', 'Flow Bytes/s', 'attack_label']]

In [13]:
flow2

,source_ip,source_port,destination_ip,destination_port,protocol,Fwd Packets/s,Bwd Packets/s,Flow Bytes/s,attack_label
0,59.166.0.0,1390,149.171.126.6,53,udp,1895.734597,1895.734597,2.805687e+05,normal
1,59.166.0.0,33661,149.171.126.9,1024,udp,110.702128,110.702128,2.302604e+04,normal
2,59.166.0.6,1464,149.171.126.7,53,udp,1787.310098,1787.310098,2.895442e+05,normal
3,59.166.0.5,3593,149.171.126.5,53,udp,1654.259719,1654.259719,2.448304e+05,normal
4,59.166.0.3,49664,149.171.126.0,53,udp,1710.863986,1710.863986,2.771600e+05,normal
...,...,...,...,...,...,...,...,...,...
2059410,59.166.0.1,38606,149.171.126.9,80,tcp,463.718456,930.976747,1.392062e+06,normal
2059411,59.166.0.1,38606,149.171.126.9,80,tcp,463.718456,930.976747,1.392062e+06,normal
2059412,59.166.0.5,33094,149.171.126.7,43433,tcp,68.723799,91.631732,2.460312e+04,normal
2059413,59.166.0.9,35433,149.171.126.0,80,tcp,26.352449,52.704897,7.703639e+04,normal
2059414,175.45.176.0,17293,149.171.126.17,110,tcp,12.725561,12.725561,1.325579e+03,exploits

In [14]:
flow1.to_csv('./cicids_flow1.csv', index=False)

In [15]:
flow2.to_csv('./unsw_flow1.csv', index=False)